// <auto-generated />
namespace WebApplication39.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dem2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dem2));
        
        string IMigrationMetadata.Id
        {
            get { return "202106271416009_dem2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
